#!/usr/bin/env bash
# a script that configures nginx on a new Ubuntu machine

# Run script with sudo powers
sudo su <<delimiter

# carry a system update
apt-get -y update

# install nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'

# Start Nginx
service nginx start

# Creating a page with "Hello World!" message
echo "Hello World!" > /var/www/html/index.html

delimiter
