#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Check if the string exists in the default Nginx configuration
if ! grep -q "Ceci n'est pas une page" /var/www/html/404.html; then
    # Create custom 404 page if it doesn't exist
    echo "Ceci n'est pas une page" > /var/www/html/404.html
fi

# Check if the configurations already exist in the Nginx configuration file
if ! grep -q "error_page 404 /404.html" /etc/nginx/sites-enabled/default; then
    # Add configuration for custom 404 page
    sudo sed -i '/listen 80 default_server;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-enabled/default
fi

# Restart Nginx
sudo service nginx restart
