#!/usr/bin/env bash
# Installing and configure HAproxy on the lb-01 server
# with roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# Configure HAProxy using roundrobin algorithm
echo "
frontend MIR_front
        bind *:80
        default_backend MIR_back

backend http_back
        balance roundrobin
        server 491478-web-01 54.227.129.59:80 check
        server 491478-web-02 54.174.120.121:80 check
">> /etc/haproxy/haproxy.cfg

# Enable HAProxy management
sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

sudo service haproxy restart
