#!/usr/bin/env bash
# a Bash script that pings an IP address 5 times
# Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if argument has not been passed

if [ "$#" -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
