#!/usr/bin/env bash
# configuring Nginx server to listen on port 80 from port 8080

sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid
