#!/usr/bin/env bash
# Displaying "To infinity and beyond" indefinitely with
#+ a 2 sleep in between each iteration.
#   Displays "I am invincible!!!" in between each iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
