#!/usr/bin/env bash
# Loops from 1 to 10 and print:
#   "bad luck" when iteration gets to the 4th
#   "good luck" when iteration gets to the 8th
#   "Best School" for all other iterations

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
